# trigger:
#   - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  - script: |
      python create_dags.py | tee output.log
    displayName: 'Run DAG Generator'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
